server:
  port: 8085
spring:
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/guli_sms
    username: root
    password: 12345
  redis:
    host: 127.0.0.1
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  mapper-locations: classpath:mapper/sms/**/*.xml